# Generated by Django 4.1 on 2023-01-22 19:43

from django.db import migrations
from django.db import transaction

def import_csv(apps, schema_editor):
    with open(r"ScrapedFoods.txt", "r") as f:
        BaseIng = apps.get_model('calculator', 'BaseIng')
        for line in f:
            vaules = line.strip().split(",")
            name = vaules[0]
            try:
                price = float(vaules[1])
            except:
                price = 0.0
            try:
                mesuerment = str(vaules[2])
            except:
                mesuerment = "g"
            with transaction.atomic():
                BaseIng.objects.create(ing_name = name,
                        price_per_unit = float(price),
                        measurement_type= mesuerment)

class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(import_csv)
    ]
