# Generated by Django 4.2.1 on 2023-05-22 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeing',
            name='test',
        ),
    ]
