# Generated by Django 4.2.1 on 2023-05-12 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0002_auto_20230122_1443'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baseing',
            old_name='price_per_unit',
            new_name='package_price',
        ),
        migrations.AddField(
            model_name='baseing',
            name='package_size',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
